config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  namespace :api do
    namespace :v1 do
      resources :events
      resources :search
      get '/children' => 'children#index'
      get '/children/trisomy_type_totals' => 'children#trisomy_type_totals'
      get '/children/birth_order_totals' => 'children#birth_order_totals'
      get '/users' => 'users#index'
      patch '/users' => 'users#update'
      patch '/children/:id' => 'children#update'
      delete '/users/:id' => 'users#destroy'
      delete '/children/:id' => 'children#destroy'

      get '/birthdays' => 'birthdays#index'
    end
  end

  devise_for :users

  root 'users#home'
  get 'children-index' => 'users#children_index'
  get 'admin-dashboard' => 'users#index'
  patch 'admin-dashboard' => 'users#update'

  resources :events

  get '/queries' => 'users#query_table'

  get '/resources' => 'resources#index'
  get '/resources/new' => 'resources#new'
  post '/resources' => 'resources#create'
  get '/resources/:id/edit' => 'resources#edit'
  patch '/resources/:id' => 'resources#update'
  delete '/resources/:id' => 'resources#destroy'

  get '/family-dashboard' => 'families#index'
  post '/families' => 'families#create'
  get '/families/new' => 'families#new'
  get '/families/:id' => 'families#show'  
  get '/families/:id/edit' => 'families#edit'
  patch '/families/:id' => 'families#update'

  post '/physicians' => 'physicians#create'
  get '/physicians/new' => 'physicians#new'
  get '/physicians/:id' => 'physicians#show'
  get '/physicians/:id/edit' => 'physicians#edit'
  patch '/physicians/:id' => 'physicians#update' 
  patch '/physicians/:id/photo' => 'physicians#update_photo'

  get '/profile/new' => 'children#new'
  post '/profile' => 'children#create'
  get '/profile/:id' => 'children#show'
  get '/profile/:id/edit' => 'children#edit'
  patch '/profile/:id' => 'children#update'
  delete '/profile/:id' => 'children#destroy'
  patch '/profile/:id/photo' => 'children#update_photo'

  get '/homepagecontents/new' => 'home_page_contents#new'
  post '/homepagecontents' => 'home_page_contents#create'
  get '/homepagecontents/:id/edit' => 'home_page_contents#edit'
  patch '/homepagecontents/:id' => 'home_page_contents#update'

  # NEW ROUTES FOR CHILD REGISTRATION:
  get 'registrations' => 'registrations#index'
  get 'registrations/:id' => 'registrations#show'
  delete 'registrations/:id' => 'registrations#destroy'
  patch '/registrations/:id' => 'registrations#update'

  get 'registrations/contact_info/new' => 'contact_info_forms#new'
  post 'registrations/contact_info' => 'contact_info_forms#create'
  get 'registrations/contact_info/:id' => 'contact_info_forms#show'
  get 'registrations/contact_info/:id/edit' => 'contact_info_forms#edit'
  patch 'registrations/contact_info/:id' => 'contact_info_forms#update'
  
  get 'registrations/background_history/new' => 'background_history_forms#new'
  post 'registrations/background_history' => 'background_history_forms#create'
  get 'registrations/background_history/:id' => 'background_history_forms#show'
  get 'registrations/background_history/:id/edit' => 'background_history_forms#edit'
  patch 'registrations/background_history/:id' => 'background_history_forms#update'

  get 'registrations/health_history/new' => 'health_history_forms#new'
  post 'registrations/health_history' => 'health_history_forms#create'
  get 'registrations/health_history/:id' => 'health_history_forms#show'
  get 'registrations/health_history/:id/edit' => 'health_history_forms#edit'  
  patch 'registrations/health_history/:id' => 'health_history_forms#update'

  get '/calendar' => 'users#calendar'

  get '/family-center' => 'family_center#index'

  get 'data-center' => 'professional_center#index'

  get '/about' => 'users#about'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :children
  has_many :families
  has_many :physicians
  
  validates :email, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :user_type, presence: true

  def full_name
    self.first_name + " " + self.last_name
  end
end

app/views/partials/_app-javascript.html.erb
<!-- JavaScript files placed at the end of the document so the pages load faster -->
<!-- ================================================== -->
<!-- Jquery and Bootstap core js files -->
<script type="text/javascript" src="/template/plugins/jquery.min.js"></script>
<script type="text/javascript" src="/template/bootstrap/js/bootstrap.min.js"></script>
<!-- Modernizr javascript -->
<script type="text/javascript" src="/template/plugins/modernizr.js"></script>
<!-- jQuery Revolution Slider  -->
<script type="text/javascript" src="/template/plugins/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
<script type="text/javascript" src="/template/plugins/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
<!-- Isotope javascript -->
<script type="text/javascript" src="/template/plugins/isotope/isotope.pkgd.min.js"></script>
<!-- Magnific Popup javascript -->
<script type="text/javascript" src="/template/plugins/magnific-popup/jquery.magnific-popup.min.js"></script>
<!-- Appear javascript -->
<script type="text/javascript" src="/template/plugins/waypoints/jquery.waypoints.min.js"></script>
<!-- Count To javascript -->
<script type="text/javascript" src="/template/plugins/jquery.countTo.js"></script>
<!-- Parallax javascript -->
<script src="/template/plugins/jquery.parallax-1.1.3.js"></script>
<!-- Contact form -->
<script src="/template/plugins/jquery.validate.js"></script>
<script type="text/javascript" src="/template/js/fusioncharts.js"></script>
<script type="text/javascript" src="/template/js/angular-fusioncharts.min.js"></script>
<!-- Google Maps javascript -->
<!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false&amp;signed_in=true"></script>
<script type="text/javascript" src="js/google.map.config.js"></script> -->
<!-- Background Video -->
<script src="/template/plugins/vide/jquery.vide.js"></script>
<!-- Owl carousel javascript -->
<script type="text/javascript" src="/template/plugins/owl-carousel/owl.carousel.js"></script>
<!-- SmoothScroll javascript -->
<script type="text/javascript" src="/template/plugins/jquery.browser.js"></script>
<script type="text/javascript" src="/template/plugins/SmoothScroll.js"></script>
<!-- Initialization of Plugins -->
<script type="text/javascript" src="/template/js/template.js"></script>
<!-- Custom Scripts -->
<script type="text/javascript" src="/template/js/custom.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

app/views/partials/_layout-head.html.erb
    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico">

    <!-- Web Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:700,400,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <link href="/template/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <link href="/template/fonts/font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Fontello CSS -->
    <link href="/template/fonts/fontello/css/fontello.css" rel="stylesheet">


    <!-- Plugins -->
    <link href="/template/plugins/magnific-popup/magnific-popup.css" rel="stylesheet">
    <link href="/template/plugins/rs-plugin/css/settings.css" rel="stylesheet">
    <link href="/template/css/animations.css" rel="stylesheet">
    <link href="/template/plugins/owl-carousel/owl.carousel.css" rel="stylesheet">
    <link href="/template/plugins/owl-carousel/owl.transitions.css" rel="stylesheet">
    <link href="/template/plugins/hover/hover-min.css" rel="stylesheet">

    <!-- The Project core CSS file -->
    <link href="/template/css/style.css" rel="stylesheet" >
    <!-- Color Scheme (In order to change the color scheme, replace the blue.css with the color scheme that you prefer)-->
    <link href="/template/css/skins/blue.css" rel="stylesheet">

    <!-- Custom css -->
    <!-- <link href="http://localhost:3000/template/css/custom.css" rel="stylesheet"> - -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.css">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/partials/_layout-header-navbar.html.erb
<!-- add class="fixed" if necesary !-->
<% if params[:controller] != "devise/sessions" && !current_page?('/users/sign_up') %>
  <nav class="navbar navbar-default" style="background-color: #F2F2F2" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="logo" style="padding-top: 15px; padding-right: 30px; padding-bottom: 15px;  text-shadow:-1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;">
          <h4><a href="/" class="logo-font link-light">Trisomy <span class="text-default">Association </span></a></h4>
        </div>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="myNavbar">
      <% if (current_page?('/') || current_page?('/resources') || current_page?('/calendar') || current_page?('/data-center') || current_page?('/family-center')) %>
        <ul class="nav navbar-nav navbar-left">
          <% if current_user && current_page?('/')%>
            <% if current_user && (current_user.user_type == "family" || current_user.user_type == "admin") %>
              <% if !current_page?('/family-center') %>
                <li><a href="/family-center"><i class="fa fa-users fa-fw" aria-hidden="true"></i>&nbsp;Family Center</a></li>
              <% end %>
            <% end %>
            <% if current_user && !current_page?('/calendar') %>
              <li><a href="/calendar"><i class="fa fa-calendar fa-fw" aria-hidden="true"></i>&nbsp; Calendar</a></li>
            <% end %>
            <% if current_user && !current_page?('/data-center') %>
                <li><a href="/data-center"><i class="fa fa-bar-chart fa-fw" aria-hidden="true"></i>&nbsp; Data Center</a></li>
            <% end %>                    
            <li><a href="/resources"><i class="fa fa-list fa-fw" aria-hidden="true"></i>&nbsp; Resources</a></li>
          <% elsif current_user %>
            <% if current_user.user_type == "family" || current_user.user_type == "admin" %>
              <% if !current_page?('/family-center') && !current_page?('/admin-dashboard') && !current_page?('/children-index') && (params[:controller] != 'families' && params[:action] != 'show') %>
                <li><a href="/family-center"><i class="fa fa-users fa-fw" aria-hidden="true"></i>&nbsp;Family Center</a></li>
              <% end %>
            <% end %>
            <% if !current_page?('/calendar') && !current_page?('/admin-dashboard') && !current_page?('/children-index') && (params[:controller] != 'families' && params[:action] != 'show') %>
              <li><a href="/calendar"><i class="fa fa-calendar fa-fw" aria-hidden="true"></i>&nbsp; Calendar</a></li>
            <% end %>
            <% if !current_page?('/data-center') && !current_page?('/admin-dashboard') && !current_page?('/children-index') && (params[:controller] != 'families' && params[:action] != 'show') %>
                <li><a href="/data-center"><i class="fa fa-bar-chart fa-fw" aria-hidden="true"></i>&nbsp; Data Center</a></li>
            <% end %>
            <% if !current_page?('/resources') && current_page?('/')  %>               
              <li><a href="/resources"><i class="fa fa-list fa-fw" aria-hidden="true"></i>&nbsp; Resources</a></li>
            <% elsif !current_page?('/resources') && !current_page?('/admin-dashboard') && !current_page?('/children-index') && (params[:controller] != 'families' && params[:action] != 'show') %>
              <li><a href="/resources"><i class="fa fa-list fa-fw" aria-hidden="true"></i>&nbsp; Resources</a></li>
            <% end %>
          <% elsif !current_user %>
            <% if !current_page?('/resources') %>
              <li><a href="/resources"><i class="fa fa-list fa-fw" aria-hidden="true"></i>&nbsp; Resources</a></li>
            <% end %>
          <% end %>
        </ul>
        <form class="navbar-form navbar-left" style="visibility: hidden;">
        </form>
      <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <% if current_user.user_type == 'family' || current_user.user_type == 'admin' %>
              <% if current_user.family_ids[0] && !current_page?('/families/'+ current_user.family_ids[0].to_s) %>
                <li><a href="/families/<%= current_user.family_ids[0] %>"><i class="fa fa-user fa-fw" aria-hidden="true"></i>&nbsp; My Family</a></li>
              <% elsif !current_page?('/families/'+ current_user.family_ids[0].to_s) && !current_page?('/families/new') %>
                <li><a href="/families/new"><i class="fa-user-circle-o" aria-hidden="true"></i>&nbsp; Create Profile</a></li>
              <% end %>
            <% elsif current_user.user_type == 'doctor' || current_user.user_type == 'admin' %> 
              <% if current_user.physician_ids[0] && !current_page?('/physicians/'+ current_user.physician_ids[0].to_s) %>
              <li><a href="/physicians/<%= current_user.physician_ids[0] %>"><i class="glyphicon glyphicon-user" aria-hidden="true"></i>&nbsp; My Profile</a></li> 
              <% elsif !current_page?('/physicians/'+ current_user.physician_ids[0].to_s) && !current_page?('/physicians/new') %>
                <li><a href="/physicians/new"><i class="fa-user-circle-o" aria-hidden="true"></i>&nbsp; Create Profile</a></li>
              <% end %>
            <% end %>
            <% if current_user.user_type == "admin" && !current_page?('/admin-dashboard')%>
              <li><a href="/admin-dashboard"><i class="fa fa-tachometer fa-fw" aria-hidden="true"></i>&nbsp; Admin Area</a></li>
            <% end %>
            <li><a href="/users/sign_out" data-method='delete'><i class="fa fa-sign-out fa-fw" aria-hidden="true"></i>&nbsp; Sign Out</a></li>

          <% elsif current_user %>
             <li><a href="/users/sign_out" data-method='delete'><i class="fa fa-sign-out fa-fw" aria-hidden="true"></i>&nbsp; Sign Out</a></li>

          <% elsif current_page?('/') || current_page?('/resources') %>
            <li><a href="/users/sign_up"><i class="fa fa-user-plus" aria-hidden="true"></i>&nbsp; Sign Up</a></li>
            <li><a href="/users/sign_in"><i class="fa fa-sign-in fa-fw" aria-hidden="true"></i>&nbsp; Log In</a></li>

          <% end %>
          
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>

app/views/partials/_layout-header-top.html.erb
<div class="header-top colored">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">

        <!-- header-top-first end -->
        <div id="header-top-first"  class="clearfix text-left">
          <nav>
            <ul class="top-nav-menu">
              <!-- li><a class="link-light " href="#"><i class="fa fa-user-md pr-5"></i>Find a Trisomy Doctor</a></li>
              <li><a class="link-light" href="#"><i class="fa fa-flask pr-5"></i>Research</a></li> -->
              <li><a class="link-light" href="#">About Us</a></li>
              <li><a class="link-light" href="#">Media</a></li>
              <li><a class="link-light" href="#"><i class="fa fa-info-circle pr-5"></i>FAQ</a></li>
              <li><a class="link-light" href="#">Get Support</a></li>
              <li><a class="link-light" href="#">Contact Us</a></li>
              <li><a class="link-light" href="#">Donate</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_layout-header.html.erb
<!-- add class="fixed" if necesary !-->
<header class="header clearfix">

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2">
        <!-- header-left start -->
        <!-- ================ -->
        <div class="header-left clearfix" style="padding-top:45px;">

          <!-- logo -->
          <div id="link-container">
            <a href="/" id="link">Trisomy Association</a>
          </div>

          <!-- name-and-slogan -->
          <!-- <div class="site-slogan">
            Multipurpose HTML5 Template
          </div> -->

        </div>
        <!-- header-left end -->

      </div>
      <div class="col-md-8 slide-show-container">
        <%= render '/partials/slide-show' %>
      </div>
      <div class="col-md-2">
        <div style="padding-top:30px;" class="header-right clearfix">
        <!-- Devise logout / login links !-->
        <% if user_signed_in? && current_user.user_type == "doctor" %>
          <h3 align="center"><%= link_to('Create Profile', "/physicians") %></h3>
          <h3 align="center"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></h3>
        <% elsif user_signed_in? && current_user.user_type == "family" %>
          <h3 align="center"><%= link_to('Create Profile', profile_new_path) %></h3>
          <h3 align="center"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></h3>
        <% elsif user_signed_in? && current_user.user_type == "admin" %>
          <h3 align="center"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></h3>
        <% else %>
          <h3 align="center"><%= link_to('Login', new_user_session_path)  %></h3>
          <h3 align="center"><%= link_to('Sign up', new_user_registration_path ) %></h3>
        <% end %>
        <!-- main-navigation start -->
        <!-- classes: -->
        <!-- "onclick": Makes the dropdowns open on click, this the default bootstrap behavior e.g. class="main-navigation onclick" -->
        <!-- "animated": Enables animations on dropdowns opening e.g. class="main-navigation animated" -->
        <!-- "with-dropdown-buttons": Mandatory class that adds extra space, to the main navigation, for the search and cart dropdowns -->
        </div>
      </div>
    </div>
    <div class="row">
      <div clss="col-xs-12">
        <div class="main-navigation  animated with-dropdown-buttons">
          <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">

              <!-- Toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>

              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <!-- main-menu -->
                <ul class="nav navbar-nav ">
                  <li>
                    <a href="#">Awareness Ribbons</a>
                  </li>
                  <li>
                    <a href="#">Get Involved</a>
                  </li>
                  <!-- mega-menu end -->
                  <li>
                    <a href="/calendar">Calendar</a>
                  </li>
                  <li>
                    <a href="#">Trisomy Store</a>
                  </li>
                  <li>
                    <% if current_user %>
                      <%= link_to('Family Dashboard', '/family-dashboard') %>
                    <% end %>
                  </li>
                  <li>
                    <a href="/family-center">Family Center</a>
                  </li>
                  <li>
                    <% if current_user && current_user.user_type != 'family' %>
                      <a href="/professional-center">Professional Center</a>
                    <% end %>
                  <% end %>
                  </li>
                  <li>
                    <% if current_user && current_user.user_type == 'admin' %>
                      <%= link_to('Administrator Dashboard', '/admin-dashboard') %>
                    <% end %>
                  </li>
                </ul>
                <!-- main-menu end -->

                <!-- header dropdown buttons -->
                <!-- <div class="header-dropdown-buttons">
                  <a href="#" class="btn btn-sm hidden-xs btn-default">Apointment <i class="fa fa-hospital-o pl-5"></i></a>
                  <a href="#" class="btn btn-lg visible-xs btn-block btn-default">Make an Apointment <i class="fa fa-hospital-o pl-5"></i></a>
                </div> -->
                <!-- header dropdown buttons end-->

              </div>

            </div>
          </nav>
          <!-- navbar end -->

        </div>
      </div>
    </div>
  </div>

</header>

app/views/partials/_slide-show.html.erb
<!-- <section class="main-container">
<div class="container">
  <div class="row">
    <div class="main col-md-8">

      <h3>sliders</h3>
      <div class="owl-carousel content-slider-with-controls-autoplay owl-theme" style="opacity: 1; display: block;">
        <div class="owl-wrapper-outer">
          <div class="owl-wrapper">

            <div class="owl-item" style="width: 750px;">
              <div class="overlay-container overlay-visible">
                <img src="http://htmlcoder.me/preview/the_project/v.1.3/template/images/portfolio-2.jpg" alt="">
                <div class="overlay-bottom hidden-xs">
                  <div class="text">
                    <h3 class="title">Caption Title</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum optio odio, recusandae qui minima eveniet cumque praesentium expedita sint accusamus itaque.</p>
                  </div>
                </div>
                <a href="images/portfolio-2.jpg" class="popup-img overlay-link" title="image title"><i class="icon-plus-1"></i></a>
              </div>
            </div>

            <div class="owl-item" style="width: 750px;">
              <div class="overlay-container overlay-visible">
                <img src="http://htmlcoder.me/preview/the_project/v.1.3/template/images/portfolio-2.jpg" alt="">
                <div class="overlay-bottom hidden-xs">
                  <div class="text">
                    <h3 class="title">Caption Title</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum optio odio, recusandae qui minima eveniet cumque praesentium expedita sint accusamus itaque.</p>
                  </div>
                </div>
                <a href="images/portfolio-1.jpg" class="popup-img overlay-link" title="image title"><i class="icon-plus-1"></i></a>
              </div>
            </div>

            <div class="owl-item" style="width: 750px;">
              <div class="overlay-container overlay-visible">
                <img src="http://htmlcoder.me/preview/the_project/v.1.3/template/images/portfolio-3.jpg" alt="">
                <div class="overlay-bottom hidden-xs">
                  <div class="text">
                    <h3 class="title">Caption Title</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum optio odio, recusandae qui minima eveniet cumque praesentium expedita sint accusamus itaque.</p>
                  </div>
                </div>
                <a href="images/portfolio-3.jpg" class="popup-img overlay-link" title="image title"><i class="icon-plus-1"></i></a>
              </div>
            </div>

          </div>
        </div>

        <div class="owl-controls clickable">
          <div class="owl-pagination">
            <div class="owl-page">
              <span class=""></span>
            </div>
            <div class="owl-page">
              <span class=""></span>
            </div>
            <div class="owl-page active">
              <span class=""></span>
            </div>
          </div>
          <div class="owl-buttons">
            <div class="owl-prev">prev</div>
            <div class="owl-next">next</div>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>
</section> -->