config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  namespace :api do
    namespace :v1 do
      resources :events
      resources :search
      get '/children' => 'children#index'
      get '/children/trisomy_type_totals' => 'children#trisomy_type_totals'
      get '/children/birth_order_totals' => 'children#birth_order_totals'
      get '/users' => 'users#index'
      patch '/users' => 'users#update'
      patch '/children/:id' => 'children#update'
      delete '/users/:id' => 'users#destroy'
      delete '/children/:id' => 'children#destroy'

      get '/birthdays' => 'birthdays#index'
    end
  end

  devise_for :users

  root 'users#home'
  get 'children-index' => 'users#children_index'
  get 'admin-dashboard' => 'users#index'
  patch 'admin-dashboard' => 'users#update'

  resources :events

  get '/queries' => 'users#query_table'

  get '/resources' => 'resources#index'
  get '/resources/new' => 'resources#new'
  post '/resources' => 'resources#create'
  get '/resources/:id/edit' => 'resources#edit'
  patch '/resources/:id' => 'resources#update'
  delete '/resources/:id' => 'resources#destroy'

  get '/family-dashboard' => 'families#index'
  post '/families' => 'families#create'
  get '/families/new' => 'families#new'
  get '/families/:id' => 'families#show'  
  get '/families/:id/edit' => 'families#edit'
  patch '/families/:id' => 'families#update'

  post '/physicians' => 'physicians#create'
  get '/physicians/new' => 'physicians#new'
  get '/physicians/:id' => 'physicians#show'
  get '/physicians/:id/edit' => 'physicians#edit'
  patch '/physicians/:id' => 'physicians#update' 
  patch '/physicians/:id/photo' => 'physicians#update_photo'

  get '/profile/new' => 'children#new'
  post '/profile' => 'children#create'
  get '/profile/:id' => 'children#show'
  get '/profile/:id/edit' => 'children#edit'
  patch '/profile/:id' => 'children#update'
  delete '/profile/:id' => 'children#destroy'
  patch '/profile/:id/photo' => 'children#update_photo'

  get '/homepagecontents/new' => 'home_page_contents#new'
  post '/homepagecontents' => 'home_page_contents#create'
  get '/homepagecontents/:id/edit' => 'home_page_contents#edit'
  patch '/homepagecontents/:id' => 'home_page_contents#update'

  # NEW ROUTES FOR CHILD REGISTRATION:
  get 'registrations' => 'registrations#index'
  get 'registrations/:id' => 'registrations#show'
  delete 'registrations/:id' => 'registrations#destroy'
  patch '/registrations/:id' => 'registrations#update'

  get 'registrations/contact_info/new' => 'contact_info_forms#new'
  post 'registrations/contact_info' => 'contact_info_forms#create'
  get 'registrations/contact_info/:id' => 'contact_info_forms#show'
  get 'registrations/contact_info/:id/edit' => 'contact_info_forms#edit'
  patch 'registrations/contact_info/:id' => 'contact_info_forms#update'
  
  get 'registrations/background_history/new' => 'background_history_forms#new'
  post 'registrations/background_history' => 'background_history_forms#create'
  get 'registrations/background_history/:id' => 'background_history_forms#show'
  get 'registrations/background_history/:id/edit' => 'background_history_forms#edit'
  patch 'registrations/background_history/:id' => 'background_history_forms#update'

  get 'registrations/health_history/new' => 'health_history_forms#new'
  post 'registrations/health_history' => 'health_history_forms#create'
  get 'registrations/health_history/:id' => 'health_history_forms#show'
  get 'registrations/health_history/:id/edit' => 'health_history_forms#edit'  
  patch 'registrations/health_history/:id' => 'health_history_forms#update'

  get '/calendar' => 'users#calendar'

  get '/family-center' => 'family_center#index'

  get 'data-center' => 'professional_center#index'

  get '/about' => 'users#about'

end

app/views/resources/edit.html.erb
<% if @resource.errors.any?%>
<div id="error_explanation" class="alert alert-danger" role="alert">
   <%= pluralize(@resource.errors.count, "Error") %>
   <ul>
      <% @resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
   </ul>
</div>
<% end %>
<div class="container">
   <div class="row">
      <div class="col-md-6 col-md-offset-3">
         <h1 class="text-center">Edit Resource</h1>
         <hr>
         <%= form_for @resource, url: {action: "update"}, html: { multipart: true } do |f| %>
         <h5 style="color:gray">Basic Info</h5>
         <div class="form-group">
            <%= f.label :name, "Name:" %>
            <%= f.text_field :name, class: "form-control", :value => @resource.name %>
         </div>
         <div class="form-group">
            <%= f.label :url, "URL:" %>
            <%= f.text_field :url, class: "form-control", :value => @resource.url %>
         </div>
         <div>
            <%= f.label :image, "Image URL:" %>
            <%= f.text_field :image, class: "form-control", :value => @resource.image %>
         </div>
         <br>
         <div class="form-group">
            <%= f.label :state, 'State' %>
            <%= f.select("state", options_for_select(us_states, @resource.state), prompt: "-", class: "form-control") %>
         </div>
         <br>
         <div class="form-group">
            <%= f.label :purpose, "Purpose" %>
            <%= f.text_field :purpose, class: "form-control", :value => @resource.purpose %>
         </div> 
         <hr>
         <div class="form-group">
            <%= f.label :description, 'Description:' %>
            <%= f.text_area :description, :value => @resource.description, class: "form-control", row: "3" %>
         </div>
         <hr>
         <div>
         </div>
         <%= submit_tag 'Update', class: "btn btn-success btn-lg btn-block"%>
      </div>
      <!-- col-md-6 -->
   </div>
   <!-- row -->
</div>
<!-- container -->
<% end %>

app/views/resources/index.html.erb
<br>
<div class="well">
  <% if @permissions %>
    <%= link_to 'Add Resource', resources_new_path, class: "btn btn-success" %>
  <% end %>
  <br>
  <hr>  
  <%= form_tag "/resources", method: :get do %>
    <%= text_field_tag :search_term %><span style="display:inline-block; width: 0px;"></span><%= submit_tag "Search", class: "btn btn-primary", style: "height: 28px; width:90px; padding:0;"%>
  <% end %>
  <hr>  
  <h4>
    <i class="glyphicon glyphicon-filter"></i>
    Filters:
  </h4>
  Name
  <% if current_page?('/resources?sort=name&sort_order=desc') || request.original_url.split("/")[3] == "resources" || !current_page?('/resources?sort=name&sort_order=asc') %>
  | 
    <a href="/resources?sort=name&sort_order=asc" id="a_z"><i class="glyphicon glyphicon-sort-by-alphabet"></i></a>
  <% end %>
  <% if current_page?('/resources?sort=name&sort_order=asc') || !current_page?('/resources?sort=name&sort_order=desc') %>
  |
    <a href="/resources?sort=name&sort_order=desc" id="z_a"><i class="glyphicon glyphicon-sort-by-alphabet-alt"></i></a>
  <% end %>
  <br>
  Date Created
  <% if current_page?('/resources?sort=updated_at&sort_order=desc') || request.original_url.split("/")[3] == "resources" || !current_page?('/resources?sort=updated_at&sort_order=asc') %>
  |
    <a href="/resources?sort=updated_at&sort_order=asc" id="old_new"><i class="glyphicon glyphicon-sort-by-attributes-alt"></i></a>
  <% end %>

  <% if current_page?('/resources?sort=updated_at&sort_order=asc') || request.original_url.split("/")[3] == "resources" || !current_page?('/resources?sort=updated_at&sort_order=desc') %>
  |
    <a href="/resources?sort=updated_at&sort_order=desc" id="new_old"><i class="glyphicon glyphicon-sort-by-attributes"></i></a>
  <% end %>
  <br>
  <% if request.original_url.split("/")[3] != "resources" %>
    View All | <a href="/resources"><i class="glyphicon glyphicon-asterisk"></i></a>
  <% end %>
</div>
<br>
<% @resources.each do |resource| %>
  <div class="col-md-4">
    <div class="well">
      
      <h1 style="text-align: center;">
        <a href="<%= resource.url %>"><%= resource.name %>
      </a></h1>
      <br>
      <% if resource.image %>
        <img src="<%= resource.image %>" style="width:250px;height:200px; display: block; margin: auto;">
        <br>
      <% end %>
      <h4>
        Description:
      </h4>
      <p><%= resource.description %></p>
      <% if resource.state && resource.state != "" %>
        <h4>
          State:
        </h4>
        <p><%= resource.state %></p>
      <% end %>
      <% if resource.purpose && resource.purpose != "" %>
        <h4>
          Purpose:
        </h4>
        <p><%= resource.purpose %></p>
      <% end %>
      <% if current_user && current_user.user_type == 'admin' %>
        <%= link_to "Edit", "/resources/#{resource.id}/edit", class: "btn btn-info" %>
        <%= link_to "Delete", "/resources/#{resource.id}", class: "btn btn-danger", method: :delete %>
      <% end %>

    </div>
    
  </div>
<% end %>

app/views/resources/new.html.erb
<% if @resource.errors.any?%>
<div id="error_explanation" class="alert alert-danger" role="alert">
   <%= pluralize(@resource.errors.count, "Error") %>
   <ul>
      <% @resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
   </ul>
</div>
<% end %>
<div class="container">
   <div class="row">
      <div class="col-md-6 col-md-offset-3">
         <h1 class="text-center">Add Resource</h1>
         <hr>
         <%= form_for @resource, url: {action: "create"} do |f| %>
         <h5 style="color:gray">Basic Info</h5>
         <div class="form-group">
            <%= f.label :name, "Name:" %>
            <%= f.text_field :name, class: "form-control" %>
         </div>
         <div class="form-group">
            <%= f.label :url, "URL:" %>
            <%= f.text_field :url, class: "form-control" %>
         </div>
         <div class="form-group">
            <%= f.label :image, "Image URL:" %>
            <%= f.text_field :image, class: "form-control" %>
         </div>
         <br>
         <div class="form-group">
            <%= f.label :state, 'State' %>
            <%= f.select("state", options_for_select(us_states), prompt: "-", class: "form-control") %>
         </div>
         <br>
         <div class="form-group">
            <%= f.label :purpose, "Purpose" %>
            <%= f.text_field :purpose, class: "form-control" %>
         </div> 
         <hr>
         <div class="form-group">
            <%= f.label :description, "Description:" %>
            <%= f.text_area :description, class: "form-control", row: "3"%>
         </div>
         <%= submit_tag 'Create', class: "btn btn-success btn-lg btn-block"%>
      <% end %>
      </div>
      <!-- col-md-6 -->
   </div>
   <!-- row -->
</div>
<!-- container -->